version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5030:5030"

  messaging:
    build:
      context: ./messaging
      dockerfile: Dockerfile
    ports:
      - "6000:6000"

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - database

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: management
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: