services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:5000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"

  messaging:
    build:
      context: ./messaging
      dockerfile: Dockerfile
    ports:
      - "${MESSAGING_PORT}:6000"

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "${AUTH_PORT}:4000"
    depends_on:
      - database

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: management
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: