version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - database

  messaging:
    build:
      context: .
      dockerfile: messaging/Dockerfile
    ports:
      - "6000:6000"

  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: management
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: