FROM postgres:15-alpine

# Configure environment variables for the database
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=management

# Expose the database port
EXPOSE 5432

CMD ["postgres"]